# Generated by Django 3.0.4 on 2020-03-11 14:31

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('registeredDate', models.DateTimeField(auto_now=True)),
                ('exit_time', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('arrival_time', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('progress', models.IntegerField()),
                ('time_spent', models.IntegerField()),
                ('ideal_time', models.IntegerField()),
                ('last_update', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField()),
                ('description', models.CharField(max_length=100000)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('DOING', 'DOING'), ('CLOSED', 'CLOSED'), ('CHECKING', 'CHECKING'), ('REVIEW', 'REVIEW')], max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('NORMAL', 'NORMAL'), ('HIGH', 'HIGH'), ('VERY-HIGH', 'VERY-HIGH'), ('IMMEDIATE', 'IMMEDIATE')], max_length=50)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peygiraneh.Employee')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='peygiraneh.Employee')),
            ],
        ),
    ]
